services:
  - type: web
    name: earnton-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: APP_IS_WEBHOOK
        value: "true"
      - key: APP_PORT
        value: "10000"
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: APP_BASE_URL
        fromSecret: APP_BASE_URL
    healthCheckPath: "/health"
    autoDeploy: true
